name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # publish to GitHub Packages
      id-token: write # provenance
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          registry-url: https://npm.pkg.github.com
          scope: "@mathieu-talarian"
          cache: 'yarn'
      - run: yarn install --immutable
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
